# Site settings
title: Gaussian Process Summer School 2013
email: 
description: > # this means to ignore newlines until "baseurl:"
  The first Gaussian Process Summer School held at the University of Sheffield in 2013.
baseurl: "/gpss13" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool
analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Nicolas Durrande, url: "https://sites.google.com/site/nicolasdurrandehomepage/"}
  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  schoolphoto: attendees.jpg
  name: Gaussian Process Summer School
  location: University of Sheffield, UK
  year: 2013
  dates:
  - {date: 10, day: Monday, month: June, year: 2013}
  - {date: 11, day: Tuesday, month: June, year: 2013}
  - {date: 12, day: Wednesday, month: June, year: 2013}
  - {date: 13, day: Thursday, month: June, year: 2013}
  
# Build settings
markdown: kramdown
